{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "user_count{method=\"active\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(auth_count{method=\"successful\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_count{method=\"failed\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "HTTP Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"get\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"delete\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"post\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\", method=\"put\"}[1m])",
     "legendFormat": "PUT"
    },
    {
     "expr": "sum by(source) (rate(request_total{source=\"jwt-pizza-service\"}[1m]))",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{method=\"cpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_usage{method=\"memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "request{method=\"latency\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(order_count{method=\"pizza\"}[1m])",
     "legendFormat": "Pizzas Purchases"
    },
    {
     "expr": "rate(order_count{method=\"failed\"}[1m])",
     "legendFormat": "Purchases Failed"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "order_amount{method=\"revenue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "order{method=\"latency\"}",
     "legendFormat": "Request Latency"
    }
   ]
  },
  {
   "title": "Pizza Logs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  }
 ]
}